using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Media;
using ExDesign.Datas;
using ExDesign.Scripts;

namespace ExDesign.Datas
{
    public class SoilData
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
        public SoilRockTypes SoilRockType { get; set; }
        public SoilTypes SoilType { get; set; }
        public RockTypes RockType { get; set; }
        public SoilDenseTypes SoilDenseType { get; set; }
        public SoilStiffTypes SoilStiffType { get; set; }
        public SiltTypes SiltType { get; set; }
        public RockSubTypes RockSubType { get; set; }
        public double NaturalUnitWeight { get; set; }
        public double SaturatedUnitWeight { get; set; }
        public int SoilStressStateIndex { get; set; }
        public int SoilStateKoIndex { get; set; }
        public double SoilFrictionAngle { get; set; }
        public double EffectiveCohesion { get; set; }
        public double UndrainedShearStrength { get; set; }
        public double WallSoilFrictionAngle { get; set; }
        public double WallSoilAdhesion { get; set; }
        public double PoissonRatio { get; set; }
        public double K0 { get; set; }
        public double Ocr { get; set; }
        public double OedometricModulus { get; set; }
        public double CohesionFactor { get; set; }
        public double YoungModulus { get; set; }
        public bool isDefault { get; set; }
        public bool isUserDefined { get; set; }
        public bool isSoilTexture { get; set; }
        public SoilTextureData SoilTexture { get; set; }
        public Color SoilColor  { get; set; }
        public object Clone()
        {
            var clone = (SoilData)this.MemberwiseClone();
            return clone;
        }
    }
    
    public static class SoilLibrary
    {
        public static ObservableCollection<SoilData> SoilDataList = new ObservableCollection<SoilData>();
        public static ObservableCollection<SoilData> SavedSoilDataList = new ObservableCollection<SoilData>();
        public static string Path = System.AppDomain.CurrentDomain.BaseDirectory.ToString() + "SoilLibrary.gexdb";
        public static string Path1 = System.AppDomain.CurrentDomain.BaseDirectory.ToString() + "SavedSoils.gexdb";
        public static void SoilLibraryDataReader()
        {
            if (!File.Exists(Path))
            {
                SoilData soil1 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Gevşek Kum", NaturalUnitWeight = 18, SaturatedUnitWeight = 18.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 27, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 18, WallSoilAdhesion = 0, PoissonRatio = 0.3, K0 = 0.55, Ocr = 1, OedometricModulus = 8000, CohesionFactor = 1, YoungModulus = 5900, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 0, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil2 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Orta Sıkı Kum", NaturalUnitWeight = 18.7, SaturatedUnitWeight = 19.2, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 31, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20.7, WallSoilAdhesion = 0, PoissonRatio = 0.3, K0 = 0.48, Ocr = 1, OedometricModulus = 20000, CohesionFactor = 1, YoungModulus = 14900, isSoilTexture = false, SoilColor = Color.FromArgb(50, 50, 50, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil3 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Sıkı Kum", NaturalUnitWeight = 19.7, SaturatedUnitWeight = 20.2, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 34, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 22.7, WallSoilAdhesion = 0, PoissonRatio = 0.3, K0 = 0.44, Ocr = 1, OedometricModulus = 45000, CohesionFactor = 1, YoungModulus = 33400, isSoilTexture = false, SoilColor = Color.FromArgb(50, 100, 100, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil4 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Gevşek Kum", NaturalUnitWeight = 18, SaturatedUnitWeight = 18.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 28, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 18.7, WallSoilAdhesion = 0, PoissonRatio = 0.3, K0 = 0.53, Ocr = 1, OedometricModulus = 10000, CohesionFactor = 1, YoungModulus = 7400, isSoilTexture = false, SoilColor = Color.FromArgb(50, 150, 150, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil5 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Orta Sıkı Kum", NaturalUnitWeight = 19.2, SaturatedUnitWeight = 19.4, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 33, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 22, WallSoilAdhesion = 0, PoissonRatio = 0.3, K0 = 0.46, Ocr = 1, OedometricModulus = 30000, CohesionFactor = 1, YoungModulus = 22300, isSoilTexture = false, SoilColor = Color.FromArgb(50, 200, 200, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil6 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Sıkı Kum", NaturalUnitWeight = 19.7, SaturatedUnitWeight = 20.2, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 36, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 24, WallSoilAdhesion = 0, PoissonRatio = 0.3, K0 = 0.41, Ocr = 1, OedometricModulus = 65000, CohesionFactor = 1, YoungModulus = 48300, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 250, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil7 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Siltli Gevşek Kum", NaturalUnitWeight = 18, SaturatedUnitWeight = 18.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 27, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 18, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.55, Ocr = 1, OedometricModulus = 7000, CohesionFactor = 1, YoungModulus = 4400, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 250, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil8 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Siltli Orta Sıkı Kum", NaturalUnitWeight = 18.3, SaturatedUnitWeight = 18.7, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 30, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.5, Ocr = 1, OedometricModulus = 17500, CohesionFactor = 1, YoungModulus = 10900, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 125, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil9 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Siltli Sıkı Kum", NaturalUnitWeight = 19.2, SaturatedUnitWeight = 19.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 32, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 21.3, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.47, Ocr = 1, OedometricModulus = 27.5, CohesionFactor = 1, YoungModulus = 17.1, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 175, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil10 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Siltli Gevşek Kum", NaturalUnitWeight = 18, SaturatedUnitWeight = 18.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 27, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 18, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.55, Ocr = 1, OedometricModulus = 6000, CohesionFactor = 1, YoungModulus = 3700, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 225, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil11 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Siltli Orta Sıkı Kum", NaturalUnitWeight = 18.3, SaturatedUnitWeight = 18.7, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 29, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 19.3, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.52, Ocr = 1, OedometricModulus = 16500, CohesionFactor = 1, YoungModulus = 10300, isSoilTexture = false, SoilColor = Color.FromArgb(50, 125, 0, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil12 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Siltli Sıkı Kum", NaturalUnitWeight = 19, SaturatedUnitWeight = 19.4, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 31, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20.7, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.48, Ocr = 1, OedometricModulus = 25000, CohesionFactor = 1, YoungModulus = 15600, isSoilTexture = false, SoilColor = Color.FromArgb(50, 175, 0, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil13 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Killi Gevşek Kum", NaturalUnitWeight = 18, SaturatedUnitWeight = 18.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 27, EffectiveCohesion = 0.5, UndrainedShearStrength = 0, WallSoilFrictionAngle = 18, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.55, Ocr = 1, OedometricModulus = 8000, CohesionFactor = 1, YoungModulus = 5000, isSoilTexture = false, SoilColor = Color.FromArgb(50, 225, 0, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil14 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Killi Orta Sıkı Kum", NaturalUnitWeight = 18.5, SaturatedUnitWeight = 19, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 28.5, EffectiveCohesion = 0.5, UndrainedShearStrength = 0, WallSoilFrictionAngle = 19, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.52, Ocr = 1, OedometricModulus = 17500, CohesionFactor = 1, YoungModulus = 10900, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 0, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil15 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Killi Sıkı Kum", NaturalUnitWeight = 19.2, SaturatedUnitWeight = 19.7, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 31, EffectiveCohesion = 0.5, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20.7, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.48, Ocr = 1, OedometricModulus = 30000, CohesionFactor = 1, YoungModulus = 18700, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 50, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil16 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Killi Gevşek Kum", NaturalUnitWeight = 18, SaturatedUnitWeight = 18.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 26, EffectiveCohesion = 0.5, UndrainedShearStrength = 0, WallSoilFrictionAngle = 17.3, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.56, Ocr = 1, OedometricModulus = 6000, CohesionFactor = 1, YoungModulus = 3700, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 100, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil17 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Killi Orta Sıkı Kum", NaturalUnitWeight = 18.4, SaturatedUnitWeight = 18.9, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 28, EffectiveCohesion = 0.5, UndrainedShearStrength = 0, WallSoilFrictionAngle = 18.7, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.53, Ocr = 1, OedometricModulus = 17000, CohesionFactor = 1, YoungModulus = 10600, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 150, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil18 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Killi Sıkı Kum", NaturalUnitWeight = 18, SaturatedUnitWeight = 18.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 30, EffectiveCohesion = 0.5, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.5, Ocr = 1, OedometricModulus = 27500, CohesionFactor = 1, YoungModulus = 17100, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 200, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil19 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Gevşek Killi Kum", NaturalUnitWeight = 18.3, SaturatedUnitWeight = 18.7, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 23, EffectiveCohesion = 1, UndrainedShearStrength = 0, WallSoilFrictionAngle = 15.3, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.61, Ocr = 1, OedometricModulus = 6000, CohesionFactor = 1, YoungModulus = 3700, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 0, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil20 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Orta Sıkı Killi Kum", NaturalUnitWeight = 19, SaturatedUnitWeight = 19.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 27, EffectiveCohesion = 1.5, UndrainedShearStrength = 0, WallSoilFrictionAngle = 18, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.55, Ocr = 1, OedometricModulus = 16000, CohesionFactor = 1, YoungModulus = 10000, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 250, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil21 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Sıkı Killi Kum", NaturalUnitWeight = 19.4, SaturatedUnitWeight = 20, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 29, EffectiveCohesion = 2, UndrainedShearStrength = 0, WallSoilFrictionAngle = 19.3, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.52, Ocr = 1, OedometricModulus = 22500, CohesionFactor = 1, YoungModulus = 14000, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 50, 50), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil22 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Gevşek Siltli Kum", NaturalUnitWeight = 17.8, SaturatedUnitWeight = 18.3, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 25, EffectiveCohesion = 0.3, UndrainedShearStrength = 0, WallSoilFrictionAngle = 16.7, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.58, Ocr = 1, OedometricModulus = 5000, CohesionFactor = 1, YoungModulus = 3100, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 100, 100), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil23 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Orta Sıkı Siltli Kum", NaturalUnitWeight = 18.5, SaturatedUnitWeight = 19.1, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 28, EffectiveCohesion = 0.3, UndrainedShearStrength = 0, WallSoilFrictionAngle = 18.7, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.53, Ocr = 1, OedometricModulus = 14500, CohesionFactor = 1, YoungModulus = 9000, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 150, 150), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil24 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Sand, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Sıkı Siltli Kum", NaturalUnitWeight = 18.9, SaturatedUnitWeight = 19.2, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 31, EffectiveCohesion = 0.3, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20.7, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.48, Ocr = 1, OedometricModulus = 20000, CohesionFactor = 1, YoungModulus = 12500, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 200, 200), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil25 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Gevşek Çakıl", NaturalUnitWeight = 19, SaturatedUnitWeight = 19.2, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 30, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20, WallSoilAdhesion = 0, PoissonRatio = 0.23, K0 = 0.5, Ocr = 1, OedometricModulus = 25000, CohesionFactor = 1, YoungModulus = 21600, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 0, 100), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil26 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Orta Sıkı Çakıl", NaturalUnitWeight = 19.5, SaturatedUnitWeight = 19.7, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 33, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 22, WallSoilAdhesion = 0, PoissonRatio = 0.23, K0 = 0.46, Ocr = 1, OedometricModulus = 70000, CohesionFactor = 1, YoungModulus = 60400, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 0, 150), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil27 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Sıkı Çakıl", NaturalUnitWeight = 20, SaturatedUnitWeight = 20.2, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 36, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 24, WallSoilAdhesion = 0, PoissonRatio = 0.23, K0 = 0.41, Ocr = 1, OedometricModulus = 125000, CohesionFactor = 1, YoungModulus = 107800, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 0, 200), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil28 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Gevşek Çakıl", NaturalUnitWeight = 19.4, SaturatedUnitWeight = 19.6, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 31, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20.7, WallSoilAdhesion = 0, PoissonRatio = 0.23, K0 = 0.48, Ocr = 1, OedometricModulus = 32500, CohesionFactor = 1, YoungModulus = 28000, isSoilTexture = false, SoilColor = Color.FromArgb(50, 250, 0, 250), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil29 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Orta Sıkı Çakıl", NaturalUnitWeight = 19.8, SaturatedUnitWeight = 20, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 35, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 23.3, WallSoilAdhesion = 0, PoissonRatio = 0.23, K0 = 0.43, Ocr = 1, OedometricModulus = 90000, CohesionFactor = 1, YoungModulus = 77600, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 250, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil30 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Sıkı Çakıl ", NaturalUnitWeight = 21, SaturatedUnitWeight = 21.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 39, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 26, WallSoilAdhesion = 0, PoissonRatio = 0.23, K0 = 0.37, Ocr = 1, OedometricModulus = 185000, CohesionFactor = 1, YoungModulus = 159600, isSoilTexture = false, SoilColor = Color.FromArgb(50, 75, 250, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil31 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Gevşek Siltli Çakıl", NaturalUnitWeight = 19.2, SaturatedUnitWeight = 19.4, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 29, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 19.3, WallSoilAdhesion = 0, PoissonRatio = 0.25, K0 = 0.52, Ocr = 1, OedometricModulus = 25000, CohesionFactor = 1, YoungModulus = 20800, isSoilTexture = false, SoilColor = Color.FromArgb(50, 125, 250, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil32 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Orta Sıkı Siltli Çakıl", NaturalUnitWeight = 19.6, SaturatedUnitWeight = 20.0, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 31, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20.7, WallSoilAdhesion = 0, PoissonRatio = 0.25, K0 = 0.48, Ocr = 1, OedometricModulus = 50000, CohesionFactor = 1, YoungModulus = 41700, isSoilTexture = false, SoilColor = Color.FromArgb(50, 175, 250, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil33 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Sıkı Siltli Çakıl", NaturalUnitWeight = 20, SaturatedUnitWeight = 20.3, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 34, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 22.7, WallSoilAdhesion = 0, PoissonRatio = 0.25, K0 = 0.44, Ocr = 1, OedometricModulus = 95000, CohesionFactor = 1, YoungModulus = 79200, isSoilTexture = false, SoilColor = Color.FromArgb(50, 225, 250, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil34 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Gevşek Siltli Çakıl", NaturalUnitWeight = 19, SaturatedUnitWeight = 19.2, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 29, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 19.3, WallSoilAdhesion = 0, PoissonRatio = 0.25, K0 = 0.52, Ocr = 1, OedometricModulus = 23000, CohesionFactor = 1, YoungModulus = 19200, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 250, 75), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil35 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Orta Sıkı Siltli Çakıl", NaturalUnitWeight = 19.6, SaturatedUnitWeight = 20, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 31, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20.7, WallSoilAdhesion = 0, PoissonRatio = 0.25, K0 = 0.48, Ocr = 1, OedometricModulus = 47500, CohesionFactor = 1, YoungModulus = 39600, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 250, 125), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil36 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Sıkı Siltli Çakıl", NaturalUnitWeight = 20, SaturatedUnitWeight = 20.3, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 33, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 22, WallSoilAdhesion = 0, PoissonRatio = 0.25, K0 = 0.46, Ocr = 1, OedometricModulus = 90000, CohesionFactor = 1, YoungModulus = 75000, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 250, 150), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil37 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Gevşek Killi Çakıl", NaturalUnitWeight = 19.3, SaturatedUnitWeight = 19.6, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 29, EffectiveCohesion = 0.4, UndrainedShearStrength = 0, WallSoilFrictionAngle = 19.3, WallSoilAdhesion = 0, PoissonRatio = 0.25, K0 = 0.52, Ocr = 1, OedometricModulus = 25000, CohesionFactor = 1, YoungModulus = 20800, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 250, 200), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil38 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Orta Sıkı Killi Çakıl", NaturalUnitWeight = 19.7, SaturatedUnitWeight = 20, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 31, EffectiveCohesion = 0.4, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20.7, WallSoilAdhesion = 0, PoissonRatio = 0.25, K0 = 0.48, Ocr = 1, OedometricModulus = 50000, CohesionFactor = 1, YoungModulus = 41700, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 250, 250), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil39 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "İyi Derecelenmiş Sıkı Killi Çakıl", NaturalUnitWeight = 20, SaturatedUnitWeight = 20.4, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 34, EffectiveCohesion = 0.4, UndrainedShearStrength = 0, WallSoilFrictionAngle = 22.7, WallSoilAdhesion = 0, PoissonRatio = 0.25, K0 = 0.44, Ocr = 1, OedometricModulus = 95000, CohesionFactor = 1, YoungModulus = 79200, isSoilTexture = false, SoilColor = Color.FromArgb(50, 100, 100, 175), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil40 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Gevşek Killi Çakıl", NaturalUnitWeight = 19.3, SaturatedUnitWeight = 19.6, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 28, EffectiveCohesion = 0.4, UndrainedShearStrength = 0, WallSoilFrictionAngle = 18.7, WallSoilAdhesion = 0, PoissonRatio = 0.25, K0 = 0.53, Ocr = 1, OedometricModulus = 23000, CohesionFactor = 1, YoungModulus = 19200, isSoilTexture = false, SoilColor = Color.FromArgb(50, 125, 125, 225), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil41 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Orta Sıkı Killi Çakıl", NaturalUnitWeight = 19.7, SaturatedUnitWeight = 20, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 30, EffectiveCohesion = 0.4, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20, WallSoilAdhesion = 0, PoissonRatio = 0.25, K0 = 0.5, Ocr = 1, OedometricModulus = 50000, CohesionFactor = 1, YoungModulus = 41700, isSoilTexture = false, SoilColor = Color.FromArgb(50, 75, 75, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil42 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Kötü Derecelenmiş Sıkı Killi Çakıl", NaturalUnitWeight = 20, SaturatedUnitWeight = 20.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 33, EffectiveCohesion = 0.4, UndrainedShearStrength = 0, WallSoilFrictionAngle = 22, WallSoilAdhesion = 0, PoissonRatio = 0.25, K0 = 0.46, Ocr = 1, OedometricModulus = 95000, CohesionFactor = 1, YoungModulus = 79200, isSoilTexture = false, SoilColor = Color.FromArgb(50, 255, 175, 175), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil43 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Gevşek Killi Çakıl", NaturalUnitWeight = 19.4, SaturatedUnitWeight = 19.7, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 27, EffectiveCohesion = 1, UndrainedShearStrength = 0, WallSoilFrictionAngle = 18, WallSoilAdhesion = 0, PoissonRatio = 0.3, K0 = 0.55, Ocr = 1, OedometricModulus = 22500, CohesionFactor = 1, YoungModulus = 16700, isSoilTexture = false, SoilColor = Color.FromArgb(50, 255, 125, 125), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil44 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Orta Sıkı Killi Çakıl", NaturalUnitWeight = 19.7, SaturatedUnitWeight = 20.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 30, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20, WallSoilAdhesion = 0, PoissonRatio = 0.3, K0 = 0.5, Ocr = 1, OedometricModulus = 40000, CohesionFactor = 1, YoungModulus = 29700, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 250, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil45 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Sıkı Killi Çakıl", NaturalUnitWeight = 20.5, SaturatedUnitWeight = 21.5, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 32, EffectiveCohesion = 0, UndrainedShearStrength = 0, WallSoilFrictionAngle = 21.5, WallSoilAdhesion = 0, PoissonRatio = 0.3, K0 = 0.47, Ocr = 1, OedometricModulus = 70000, CohesionFactor = 1, YoungModulus = 52000, isSoilTexture = false, SoilColor = Color.FromArgb(50, 255, 75, 75), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil46 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Gevşek Siltli Çakıl", NaturalUnitWeight = 19, SaturatedUnitWeight = 19.2, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 29, EffectiveCohesion = 0.2, UndrainedShearStrength = 0, WallSoilFrictionAngle = 19.2, WallSoilAdhesion = 0, PoissonRatio = 0.3, K0 = 0.52, Ocr = 1, OedometricModulus = 21500, CohesionFactor = 1, YoungModulus = 16000, isSoilTexture = false, SoilColor = Color.FromArgb(50, 0, 250, 0), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil47 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Orta Sıkı Siltli Çakıl", NaturalUnitWeight = 19.4, SaturatedUnitWeight = 19.8, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 31, EffectiveCohesion = 0.3, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20.7, WallSoilAdhesion = 0, PoissonRatio = 0.3, K0 = 0.48, Ocr = 1, OedometricModulus = 45000, CohesionFactor = 1, YoungModulus = 33400, isSoilTexture = false, SoilColor = Color.FromArgb(50, 100, 200, 255), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil48 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Gravel, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.None, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Sıkı Siltli Çakıl", NaturalUnitWeight = 20, SaturatedUnitWeight = 20.2, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 33, EffectiveCohesion = 0.3, UndrainedShearStrength = 0, WallSoilFrictionAngle = 22, WallSoilAdhesion = 0, PoissonRatio = 0.3, K0 = 0.46, Ocr = 1, OedometricModulus = 80000, CohesionFactor = 1, YoungModulus = 59400, isSoilTexture = false, SoilColor = Color.FromArgb(50, 50, 150, 225), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil49 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Silt, SoilDenseType = SoilDenseTypes.Loose, SiltType = SiltTypes.NonPlastic, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Non-Plastik Gevşek Silt", NaturalUnitWeight = 17.5, SaturatedUnitWeight = 18.0, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 23, EffectiveCohesion = 0.2, UndrainedShearStrength = 0, WallSoilFrictionAngle = 15.3, WallSoilAdhesion = 0, PoissonRatio = 0.37, K0 = 0.61, Ocr = 1, OedometricModulus = 4500, CohesionFactor = 1, YoungModulus = 2500, isSoilTexture = false, SoilColor = Color.FromArgb(50, 125, 250, 65), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil50 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Silt, SoilDenseType = SoilDenseTypes.MediumDense, SiltType = SiltTypes.NonPlastic, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Non-Plastik Orta Sıkı Silt", NaturalUnitWeight = 18.2, SaturatedUnitWeight = 18.6, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 27, EffectiveCohesion = 0.3, UndrainedShearStrength = 0, WallSoilFrictionAngle = 18, WallSoilAdhesion = 0, PoissonRatio = 0.37, K0 = 0.55, Ocr = 1, OedometricModulus = 10000, CohesionFactor = 1, YoungModulus = 5700, isSoilTexture = false, SoilColor = Color.FromArgb(50, 150, 250, 100), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };
                SoilData soil51 = new SoilData() { ID = Guid.NewGuid(), isUserDefined = false, isDefault = true, SoilRockType = SoilRockTypes.Soil, SoilType = SoilTypes.Silt, SoilDenseType = SoilDenseTypes.Dense, SiltType = SiltTypes.NonPlastic, SoilStiffType = SoilStiffTypes.None, RockType = RockTypes.None, RockSubType = RockSubTypes.None, Name = "Non-Plastik Sıkı Silt", NaturalUnitWeight = 18.4, SaturatedUnitWeight = 18.8, SoilStressStateIndex = 0, SoilStateKoIndex = 0, SoilFrictionAngle = 30, EffectiveCohesion = 0.5, UndrainedShearStrength = 0, WallSoilFrictionAngle = 20, WallSoilAdhesion = 0, PoissonRatio = 0.35, K0 = 0.5, Ocr = 1, OedometricModulus = 25000, CohesionFactor = 1, YoungModulus = 14100, isSoilTexture = false, SoilColor = Color.FromArgb(50, 75, 250, 75), SoilTexture = SoilTexture.tempSoilTextureDataList[0], };






                List<SoilData> tempList = new List<SoilData>();
                tempList.Add(soil1);
                tempList.Add(soil2);
                tempList.Add(soil3);
                tempList.Add(soil4);
                tempList.Add(soil5);
                tempList.Add(soil6);
                tempList.Add(soil7);
                tempList.Add(soil8);
                tempList.Add(soil9);
                tempList.Add(soil10);
                tempList.Add(soil11);
                tempList.Add(soil12);
                tempList.Add(soil13);
                tempList.Add(soil14);
                tempList.Add(soil15);
                tempList.Add(soil16);
                tempList.Add(soil17);
                tempList.Add(soil18);
                tempList.Add(soil19);
                tempList.Add(soil20);
                tempList.Add(soil21);
                tempList.Add(soil22);
                tempList.Add(soil23);
                tempList.Add(soil24);
                tempList.Add(soil25);
                tempList.Add(soil26);
                tempList.Add(soil27);
                tempList.Add(soil28);
                tempList.Add(soil29);
                tempList.Add(soil30);
                tempList.Add(soil31);
                tempList.Add(soil32);
                tempList.Add(soil33);
                tempList.Add(soil34);
                tempList.Add(soil35);
                tempList.Add(soil36);
                tempList.Add(soil37);
                tempList.Add(soil38);
                tempList.Add(soil39);
                tempList.Add(soil40);
                tempList.Add(soil41);
                tempList.Add(soil42);
                tempList.Add(soil43);
                tempList.Add(soil44);
                tempList.Add(soil45);
                tempList.Add(soil46);
                tempList.Add(soil47);
                tempList.Add(soil48);
                tempList.Add(soil49);
                tempList.Add(soil50);
                tempList.Add(soil51);
                string json = JsonConvert.SerializeObject(tempList.ToArray());

                //write string to file
                File.WriteAllText(Path, json);
            }
            if (!File.Exists(Path1))
            {
                
                List<SoilData> tempList1 = new List<SoilData>();
                

                string json1 = JsonConvert.SerializeObject(tempList1.ToArray());

                //write string to file
                File.WriteAllText(Path1, json1);
            }
            // deserialize JSON directly from a file
            using (StreamReader file = File.OpenText(Path))
            {
                JsonSerializer serializer = new JsonSerializer();
                SoilDataList = (ObservableCollection<SoilData>)serializer.Deserialize(file, typeof(ObservableCollection<SoilData>));
            }
            // deserialize JSON directly from a file
            using (StreamReader file = File.OpenText(Path1))
            {
                JsonSerializer serializer = new JsonSerializer();
                SavedSoilDataList = (ObservableCollection<SoilData>)serializer.Deserialize(file, typeof(ObservableCollection<SoilData>));
            }
        }
        public static void SoilSave()
        {
            string json = JsonConvert.SerializeObject(SavedSoilDataList.ToArray());

            //write string to file
            File.WriteAllText(Path1, json);
        }

    }
}
